# Generated by Django 5.2.11 on 2026-02-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.TextField()),
                ('image_url', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='../images_recipe/')),
                ('ingredients', models.JSONField()),
                ('steps', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
